### PR TITLE
bugfix #47: .env should not be included in source control

### PR DESCRIPTION
**Pull request by kunal8411**

### CODE REVIEW

**Comment by schneems** [comment]
Hey, thanks for the PR! Sorry for the delay in the review.

I agree that it shouldn't be in git for security reasons generally, however the existence of that file in this case is needed for the local demo where we want to demonstrate how env vars are picked up and change the behavior of the app. This is a convention we have in our other getting started guides as well https://github.com/heroku/ruby-getting-started/blob/main/.env. 

An alternative idea could be to provide a command to remove it from git at the end of the tutorial. We could also remove it (as you've done here) and prompt the user to generate the file instead. However, I would want to make that change in docs first so the tutorial flow isn't broken. Maybe something like this

I think it's important to have secure defaults, so I would endorse eventually removing it, at the cost of an additional step to add the file in the instructions.

@SandyPantsLai, do you have opinions here?

**Comment by SandyPantsLai** [comment]
@schneems I think adding a note to the Getting Started guide and to this repo's README to explain why we've included the `.env` file in the repo purely to show an example, and users shouldn't include the file in their actual Git repo.

**Comment by schneems** [comment]
I worry that someone will follow the tutorial, then modify the app to suit their needs without realizing that they're potentially exposing secrets. Or just clone and use it directly.

I feel a note isn't strong enough to prevent this failure mode. I would prefer explicit instructions to remove the file, which, from experience are somewhat tricky and actually delete the file, so a bash invocation to preserve the file, but remove it from git would be non-trivial.

Another alternative: Add a note into the file itself like:

```
COMMENT="For a production app: Add this file to your .gitignore and remove it from your git history"
```

**Comment by colincasey** [comment]
@schneems I like the comment suggestion. Especially since it seems that there was a previous attempt in #107 to remove the `.env` which then got reverted in https://github.com/heroku/node-js-getting-started/commit/eac85fcf2e04aa43a930ad3f1914e153a8ced0ee.

**Comment by schneems** [comment]
The "dotenv" is not a documented standard, as such different tools support different things. It looks like `heroku local` supports comments:

```
$ cat .env
TIMES=10
# YOLO I AMA comment
⛄️ 3.1.4 🚀 /private/tmp/e9bbf32333695f8b531bbee99877651f/ruby-getting-started (main)
$ heroku local
[OKAY] Loaded ENV .env File as KEY=VALUE Format
12:11:51 PM web.1 |  [14199] Puma starting in cluster mode...
12:11:51 PM web.1 |  [14199] * Puma version: 6.3.1 (ruby 3.1.4-p223) ("Mugi No Toki Itaru")
12:11:51 PM web.1 |  [14199] *  Min threads: 5
12:11:51 PM web.1 |  [14199] *  Max threads: 5
12:11:51 PM web.1 |  [14199] *  Environment: development
12:11:51 PM web.1 |  [14199] *   Master PID: 14199
12:11:51 PM web.1 |  [14199] *      Workers: 2
12:11:51 PM web.1 |  [14199] *     Restarts: (✔) hot (✖) phased
12:11:51 PM web.1 |  [14199] * Preloading application
12:11:51 PM web.1 |  [14199] * Listening on http://0.0.0.0:5001
12:11:51 PM web.1 |  [14199] Use Ctrl-C to stop
12:11:51 PM web.1 |  [14199] - Worker 0 (PID: 14200) booted in 0.0s, phase: 0
12:11:51 PM web.1 |  [14199] - Worker 1 (PID: 14201) booted in 0.0s, phase: 0
^C[WARN] Interrupted by User
[DONE] Killing all processes with signal  SIGINT
12:11:56 PM web.1 |  [14199] - Gracefully shutting down workers...
```

So I think it's safe to put in an actual comment versus the "comment inside of an env var" that I did above. Something like:

```
# This .env file is checked into git for demonstration purposes only. 
# We recommend adding the `.env` file to your `.gitignore` file and removing it from git cache with the command `git rm --cached .env`
```

**Comment by colincasey** [comment]
Closing this in favor of #309

**Pull request closed without merging**
