### PR TITLE
Add scale dynos line

### PR DESCRIPTION
**Pull request by RichardLitt**

### CODE REVIEW

**Comment by jonmountjoy** [comment]
Thanks @RichardLitt but this shouldn't be necessary.  It should automatically spin up a web dyno.

**Comment by RichardLitt** [comment]
I don't remember exactly the situation, as it was a while go But I remember I needed to do this, or I wouldn't have submitted the PR.

**Comment by jonmountjoy** [comment]
I can't reproduce, so I'm closing for now.  I think there's a case when you first push an app and it's got a bug and cannot start the web dyno, that it will be necessary to scale when it's fixed.  But in this app, it should just work.  

Thank you.

**Comment by RichardLitt** [comment]
Fair enough! If anyone else runs into it, at least this is here. Cheers.

**Pull request closed without merging**
